### ISSUE TITLE
Timestamp converter in JS

### ISSUE THREAD

**Issue by ManoukK** [ManoukK/web-app-from-scratch-1920#14]
https://makitweb.com/convert-unix-timestamp-to-date-time-with-javascript/

**Comment by Ramon96** [comment]
Dit zou je ook kunnen helpen bij het converteren van timestamps naar iets leesbaars. 
https://www.epochconverter.com/programming/#javascript
Dit werkte voor mij :)

**Comment by ManoukK** [comment]
Via Ramon een handige en (veel) kortere timestamp converter gebruikt
