### ISSUE TITLE
Api informatie

### ISSUE THREAD

**Issue by Ramon96** [ManoukK/web-app-from-scratch-1920#16]
Misschien kan je nog wat vertellen over de API wat je gebruikt.
Wat voor informatie kan je eruit halen? 
Wat ben je verplan te doen met deze informatie?
Gebruik je een API Key? en hoe kan iemand die je project wil nabouwen deze verkrijgen?

**Comment by ManoukK** [comment]
Al deze punten heb ik nu beschreven in mijn readme onder de data en api kopje
