### ISSUE TITLE
Ruim code op die je niet meer gebruikt

### ISSUE THREAD

**Issue by Ramon96** [ManoukK/web-app-from-scratch-1920#17]
Ik zie dat je veel code uit gecomment hebt, dit kan best wel rommelig worden als je je project verder uit gaat breiden :(.

Wees niet bang om oude code weg te gooien, je kan op github namelijk all je oude code terug lezen als dat nodig is (en zelfs een versie terug gaan).

Die vind je tussen je commits: https://github.com/ManoukK/web-app-from-scratch-1920/commits/master

Dit is dan ook de rede dat regelmattig committen je in het voordeel zal zijn zodat je precies weet waar je op dat moment aan gewerkt hebt.
(Tip: je hoeft niet all je commits meteen te pushen, je kan zoveel nodige commits opstapelen en wanneer je dan pushed dan worden al de commits gepushed)

**Comment by ManoukK** [comment]
yes gedaan!
