### ISSUE TITLE
Probeer meer te commiten 

### ISSUE THREAD

**Issue by Ramon96** [ManoukK/web-app-from-scratch-1920#18]
Ik vind het persoonlijk fijn om af en toe te commiten. Als iets dan kapot gaat heb je teminste nog een versie waar je op terug kan vallen of kan je lezen wat er precies veranderd is wat je code mogelijk kapot heeft gemaakt.

**Comment by ManoukK** [comment]
Bedankt voor de tip! Ik ben daar nu meer op gaan letten hahah
