### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by Ramon96** [ManoukK/web-app-from-scratch-1920#19]
Super top dat je met comments uitlegt wat je doet. Je code is super goed te volgen.
Er kan nog wel gewerkt worden aan je functie namen Test() geeft mij nog niet duidelijkheid wat de functie voor mij gaat doen ;) 

super dat je je functie calls boven je functie declaratie's hebt staan en dat je niks in de global scope verwerkt.

**Comment by joostf** [comment]
Er staan geen variabelen in de globale scope, maar alle functions staan (nog) wel in de globale scope

**Comment by ManoukK** [comment]
Ik heb alle namen van functions die nergens op sloegen eruit gehaald of vervangen. Verder ga ik maandag alles in modules zetten en zullen er dan ook geen functions meer in de global scope staan.
