### ISSUE TITLE
Low Hangings Fruits 🥝🍊

### ISSUE THREAD

**Issue by robert-hoekstra** [ManoukK/web-app-from-scratch-1920#29]
Hi Manouk!

Deze issue bevat voornamelijk een lijstje van kleine tot middelgrote changes die jouw repository kunnen verbeteren.

# Readme

- [x]  Aanvullen van installatie proces

- [x] Aanvullen van 'hoe werkt de app'
- [x] Gifs! Door gifs toe te voegen van je applicatie creëer je al heel snel een leuke dynamische readme. Een tool daarvoor is [Gyazo](https://gyazo.com/). Met deze tool van je animated en static gifs genereren door een selectie te maken van je scherm.
- [x] Credits sectie voor hulp en code van medestudenten of internetbronnen. In de code staat dat al netjes aangegeven dus good busy! 

# Tech
- [x] Commented code verwijderen
- [x] Console logs verwijderen (voor live versie zijn deze overbodig)
- [x] Code opdelen in modules

**Comment by ManoukK** [comment]
Ik heb even van alles checkboxes gemaakt zodat ik het makkelijk kan afvinken

**Comment by ManoukK** [comment]
nog niet alle consoles verwijderd maar dat ga ik als laatst doen
