### ISSUE TITLE
Interaction Diagram 📈

### ISSUE THREAD

**Issue by robert-hoekstra** [ManoukK/web-app-from-scratch-1920#31]
In de interaction diagram maak je een keuze of de locatie bekend is van de gebruiker. Dat is een goede stap! Maar wat je kunt toevoegen is of de locatie wellicht al beschikbaar is in de localstorage van je applicatie. Zo hoeft je applicatie geen request meer te maken naar een geolocatie. Maar dan kan de data direct opgehaald worden. Scheelt data en tijd!

Je kunt localstorage weergeven in je diagram door een cylinder te gebruiken. Dat is de algemene vorm voor data.

Voor de rest ziet het er prima uit, hier en daar mist er nog wat maar dat geef je zelf al aan met de '...? ' in je diagram.

**p.s.** 
Volgens mij, maar dat weet ik niet zeker: je interaction diagram loopt nu dood bij render. volgens mij moet het diagram een circuit voorstellen waar je gebruiker doorheen kan navigeren op basis van zijn interacties. Je zou dan vanaf de render module weer een pijl kunnen trekken naar de applicatie zodat je de gebruiker keuzes zou kunnen blijven maken volgens het diagram.

**Comment by ManoukK** [comment]
interaction diagram is nu compleet

(ik maak geen gebruik meer van locatie)
