### ISSUE TITLE
Rubrik Check

### ISSUE THREAD

**Issue by robert-hoekstra** [ManoukK/web-app-from-scratch-1920#32]
- [x] De code bevat geen syntaxfouten en is netjes opgemaakt: voldoende
- [x] JSON data kan met een asynchrone request worden opgehaald uit een API: voldoende
- [x] JSON data kan, minimaal met de methodes; map, filter en reduce worden gemanipuleerd: voldoende? filter en reduce zijn nog niet gebruikt.
- [x] Code is correct gescoped en opgedeeld in modules die overeen komen met het actor diagram: onvoldoende
- [x] JSON data kan, al dan niet met een micro library, client side in de HTML worden gerenderd. Nadelen van het client-side renderen van HTML kunnen worden benoemd: Nadelen worden niet expliciet in readme benoemd. voldoende
- [x]  Routing & states kunnen, al dan niet met een micro library, worden gemanaged: voldoende
- [x] De user flow en object / class flow zijn visueel gemaakt: voldoende
- [x] De interface bevat feedback naar de gebruiker op het moment dat er gewacht moet worden op het laden van data: Onvoldoende

**Comment by ManoukK** [comment]
alles is compleet
