### ISSUE TITLE
API omschrijving

### ISSUE THREAD

**Issue by marissaverdonck** [ManoukK/web-app-from-scratch-1920#33]
beschrijf waar de API vandaan komt en welke data er wordt opgehaald. Marjolijn heeft dit bijvoorbeeld mooi gedaan met een uitklapfunctie. [Voorbeeld](https://github.com/MarjoleinAardewijn/web-app-from-scratch-1920)

**Comment by ManoukK** [comment]
gedaan! Het staat in mijn readme
